config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activates, only: [:edit]
  resources :password_resets,   only: [:edit, :new, :create, :update]
  resources :microposts,        only: [:create, :destroy]
  resources :relationships,     only: [:create, :destroy]
  
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:index, :show]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="row">
    <div class = "small">
      The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </div>
    <div class="info">
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </div>

</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

app/views/layouts/_header.html.erb
<header>
  <ul id="dropdown" class="dropdown-content">
    <li><%= link_to "Profile", (current_user ? user_path(current_user) : "#") %></li>
    <li><%= link_to "Settings", (current_user ? edit_user_path(current_user) : "#") %></li>
    <li class="divider"></li>
    <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
  </ul>

  <nav>
    <div class="nav-wrapper #1b5e20 green darken-4">
      <%= link_to "macro-poster", root_path, id: "logo" %>
      <ul id="nav" class="right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if current_user %>
          <li><%= link_to "Users", users_path %></li>
          <li><a class="dropdown-button" href="#!" data-activates="dropdown">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/head' %>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">

      <%= render 'shared/flash_messages' %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>

</html>